#!/bin/bash

scriptDir="$( dirname "$0" )"
absDir="$(cd "$scriptDir"; pwd)"
thisDir="$(pwd)"

usage() {
	echo `basename $0`: ERROR: $* 1>&2
	echo "usage: `basename $0` [-r file] - start a recording to create a gif at [file]"
	exit 1
}

require() {
  dependancy=$2
  if [[ -z $dependancy ]]; then
    dependancy=$1
  fi
  hash $1 2>/dev/null || { 
    echo >&2 "$1 required but it's not installed.";
    echo >&2 "run \`brew install $dependancy\` then try again.";
    exit 1; 
  }
}

init() {
  ttygifDir="$absDir/ttygif"
  if [[ -z "$(ls $ttygifDir)" ]]; then
    echo "initialising ttygif"
    (cd $absDir ; git submodule init; git submodule update) > /dev/null
    echo "done"
  fi

  if [[ ! -f "$ttygifDir/ttygif" ]]; then
    echo "making ttygif"
    (cd $ttygifDir ; make)
    echo "done"
  fi
}

installToPath() {
  echo "$absDir/terminal-gif \"\$@\"" > /usr/local/bin/terminal-gif
  chmod a+x /usr/local/bin/terminal-gif
  echo "installed into /usr/local/bin"
}

record() {
  file=$1
  if [[ -z "$file" ]]; then
    usage "no filename provided"
  fi

  if [[ "$file" != *.gif* ]]; then
    usage "filename must end in .gif"
  fi

  recordFile="$absDir/$1.record"
  tempDir="$absDir/$1.temp"
  gif="$thisDir/$1"
  ttygif="$absDir/ttygif/ttygif"
  concat="$absDir/ttygif/concat.sh"

  echo "Starting recording. Type exit to finish."
  ttyrec $recordFile
  echo "Finished recording. Creating gif $1"

  #Create images from ttyrec recording and delete recording
  mkdir $tempDir
  (cd $tempDir; $ttygif $recordFile)
  rm $recordFile

  (cd $tempDir; $concat $gif)

  rm -r $tempDir
}

init

require "convert" "imagemagick"
require "ttyrec"

case $1 in 
  install) installToPath ;;
  *) record $@ ;;
esac
